name: Static Code Analysis (ESLint)

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Run ESLint and generate XML report
        run: npx eslint . --ext .js,.ts -f junit -o eslint-report.xml

      - name: Upload ESLint XML report
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: eslint-report.xml



